collections: # Order of the table of contents on the left
  home:
    output: true
    permalink: /:path
  meta:
    output: true
    permalink: /:collection/:path
  pages:
    output: true
    permalink: /:path
longtitle: HKUST FYS
plugins:
  - jekyll-relative-links # Deletes .md relative paths when publishing
  - jekyll-remote-theme
relative_links: # Settings of jekyll-relative-links
  collections: true
  enabled: true
remote_theme: sighingnow/jekyll-gitbook
title: HKUST FYS
toc:
  enabled: true
url: "https://hkust-fys.github.io"
