collections:
  home:
    output: true
    permalink: /:path
  meta:
    output: true
    permalink: /:collection/:path
  pages:
    output: true
    permalink: /:path
longtitle: HKUST FYS
plugins:
  - jekyll-relative-links
relative_links:
  collections: true
  enabled: true
remote_theme: sighingnow/jekyll-gitbook
title: HKUST FYS
toc:
  enabled: true
